<CreateTestScreen>:
    name: "create_test"
    MDBoxLayout:
        id: content_box
        orientation: "vertical"
        padding: "20dp"
        spacing: "10dp"

        # --- Поля создания теста ---
        MDTextField:
            id: test_name
            hint_text: "Название теста"

        MDTextField:
            id: description
            hint_text: "Описание"
            multiline: True

        MDTextField:
            id: time_limit
            hint_text: "Время (в минутах)"
            input_filter: "int"

        MDTextField:
            id: passing_score
            hint_text: "Проходной балл (%)"
            input_filter: "int"

        MDTextField:
            id: attempts_limit
            hint_text: "Лимит попыток"
            input_filter: "int"

        MDBoxLayout:
            orientation: "horizontal"
            spacing: "10dp"
            size_hint_y: None
            height: "48dp"

            MDRectangleFlatButton:
                id: theme
                text: "Выберите тему"
                on_release: root.open_theme_menu()

            MDRaisedButton:
                text: "Добавить тему"
                on_release: root.open_add_theme_dialog()

            MDSpinner:
                id: theme_loader
                size_hint: None, None
                size: "30dp", "30dp"
                pos_hint: {"center_x": 0.5}
                active: False

        MDRaisedButton:
            text: "Создать тест и перейти к заданиям"
            pos_hint: {"center_x": 0.5}
            on_release: root.create_test_and_load_tasks_ui()

        MDTextField:
            id: num_tasks
            hint_text: "Количество заданий"
            input_filter: "int"
            on_text_validate: root.create_task_forms()

        ScrollView:
            size_hint: (1, 0.5)
            MDBoxLayout:
                id: tasks_container
                orientation: "vertical"
                adaptive_height: True
                spacing: "10dp"


<TaskForm>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
    spacing: "8dp"
    padding: "10dp"
    md_bg_color: app.theme_cls.bg_light

    MDTextField:
        id: question_field
        hint_text: "Вопрос"
        multiline: True
        size_hint_y: None
        height: "80dp"

    MDFlatButton:
        id: type_button
        text: "Тип: текст"
        on_release: root.open_task_type_menu()

    MDTextField:
        id: options_count_field
        hint_text: "Количество вариантов (для радио/чекбоксов)"
        input_filter: "int"
        on_text_validate: root.update_options()
        size_hint_y: None
        height: 0

    MDBoxLayout:
        id: options_container
        orientation: "vertical"
        size_hint_y: None
        height: self.minimum_height
        spacing: "4dp"