<TestTakingScreen>:
    name: "test_taking"

    MDFloatLayout:
        md_bg_color: app.rjd_light_red

        MDCard:
            size_hint: .9, .88
            pos_hint: {"center_x": .5, "top": .95}
            elevation: 2
            padding: [20, 15, 20, 15]
            spacing: 12
            orientation: "vertical"
            md_bg_color: app.rjd_white
            radius: [12]

            MDTopAppBar:
                title: "Вопрос {}/{}".format(root.current_index + 1, len(root.questions) if root.questions else 1)
                right_action_items: [["arrow-left", lambda x: root.back_to_previous()]]
                elevation: 2
                md_bg_color: app.rjd_dark_red
                specific_text_color: app.rjd_white
                font_style: "H6"
                size_hint_y: None
                height: dp(56)


            ScrollView:
                bar_width: dp(4)
                bar_color: app.rjd_dark_red

                BoxLayout:
                    id: question_container
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    padding: [10, 10, 10, 20]
                    spacing: 10

                    MDLabel:
                        id: question_label
                        text: root.questions[root.current_index]["task"]["question"] if root.questions else "Загрузка..."
                        font_style: "H6"
                        halign: "center"
                        theme_text_color: "Primary"
                        size_hint_y: None
                        height: self.texture_size[1]

                    BoxLayout:
                        id: answers_box
                        orientation: "vertical"
                        spacing: dp(10)
                        size_hint_y: None
                        height: self.minimum_height

            MDRaisedButton:
                text: "Далее"
                pos_hint: {"center_x": 0.5}
                size_hint: None, None
                size: dp(120), dp(48)
                md_bg_color: app.rjd_dark_red
                text_color: app.rjd_white
                on_press: root.submit_answer()
