# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QFont
from PyQt6.QtWidgets import QWidget
from PySide6.QtGui import QFontDatabase


class IconW(QWidget):
    sig = QtCore.pyqtSignal(int)

    def __init__(self):
        pix = ["1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png", "8.png", "9.png"]
        self.pixmap = [QtGui.QIcon('images1/' + path) for path in pix]
        super().__init__()
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.btn1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.orientir()
        self.style()
        self.connect_b()
        self.set_text()
        self.ok2 = None


    def orientir(self):
        """Определяет размеры объектов"""
        self.resize(252, 253)
        self.setFixedSize(self.size())
        self.btn1.setGeometry(QtCore.QRect(0, 0, 80, 81))
        self.btn2.setGeometry(QtCore.QRect(85, 0, 80, 81))
        self.btn3.setGeometry(QtCore.QRect(171, 0, 80, 81))

        self.btn4.setGeometry(QtCore.QRect(0, 86, 80, 81))
        self.btn5.setGeometry(QtCore.QRect(85, 86, 80, 81))
        self.btn6.setGeometry(QtCore.QRect(171, 86, 80, 81))

        self.btn7.setGeometry(QtCore.QRect(0, 172, 80, 81))
        self.btn8.setGeometry(QtCore.QRect(85, 172, 80, 81))
        self.btn9.setGeometry(QtCore.QRect(171, 172, 80, 81))


    def style(self):
        """Определяет стили объектов"""
        self.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.btn1.setIcon(self.pixmap[0])
        self.btn1.setIconSize(QtCore.QSize(79, 80))
        self.btn2.setIcon(self.pixmap[1])
        self.btn2.setIconSize(QtCore.QSize(79, 80))
        self.btn3.setIcon(self.pixmap[2])
        self.btn3.setIconSize(QtCore.QSize(79, 80))
        self.btn4.setIcon(self.pixmap[3])
        self.btn4.setIconSize(QtCore.QSize(79, 80))
        self.btn5.setIcon(self.pixmap[4])
        self.btn5.setIconSize(QtCore.QSize(79, 80))
        self.btn6.setIcon(self.pixmap[5])
        self.btn6.setIconSize(QtCore.QSize(79, 80))
        self.btn7.setIcon(self.pixmap[6])
        self.btn7.setIconSize(QtCore.QSize(79, 80))
        self.btn8.setIcon(self.pixmap[7])
        self.btn8.setIconSize(QtCore.QSize(79, 80))
        self.btn9.setIcon(self.pixmap[8])
        self.btn9.setIconSize(QtCore.QSize(79, 80))

    def connect_b(self):
        """Определяет подключение объектов"""
        self.btn1.clicked.connect(self.b1)
        self.btn2.clicked.connect(self.b2)
        self.btn3.clicked.connect(self.b3)
        self.btn4.clicked.connect(self.b4)
        self.btn5.clicked.connect(self.b5)
        self.btn6.clicked.connect(self.b6)
        self.btn7.clicked.connect(self.b7)
        self.btn8.clicked.connect(self.b8)
        self.btn9.clicked.connect(self.b9)

    def b1(self):
        self.sig.emit(0)
        self.close()

    def b2(self):
        self.sig.emit(1)
        self.close()

    def b3(self):
        self.sig.emit(2)
        self.close()

    def b4(self):
        self.sig.emit(3)
        self.close()

    def b5(self):
        self.sig.emit(4)
        self.close()

    def b6(self):
        self.sig.emit(5)
        self.close()

    def b7(self):
        self.sig.emit(6)
        self.close()

    def b8(self):
        self.sig.emit(7)
        self.close()

    def b9(self):
        self.sig.emit(8)
        self.close()

    def set_text(self):
        """Определяет отображаемый текст объектов"""
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "friend&comma"))
        self.setWindowIcon(QtGui.QIcon('icon.ico'))
        self.btn1.setText("")
        self.btn2.setText("")
        self.btn3.setText("")
        self.btn4.setText("")
        self.btn5.setText("")
        self.btn6.setText("")
        self.btn7.setText("")
        self.btn8.setText("")
        self.btn9.setText("")

