version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rgd_system
      POSTGRES_USER: rgd_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: